# **Project 1 - Data Cleaning & Preparation**

## Objective
Clean raw dataset by handling missing values,
removing duplicates, and correcting inconsistent data formats.

## Tools
- Python
- Pandas
- Google Colab

## Progress Tracking

| Phase | Status | Notes |
|---|---|---|
| Phase 1 — Initial Setup & Dataset Understanding | ✅ | |
| Phase 2 — Missing Value Analysis & Handling | ✅ | |
| Phase 3 — Duplicate Detection & Removal | ✅ | |
| Phase 4 — Data Formatting, Cleaning, & Validation | ✅ | |
| Phase 5 — Data Validation | ✅ | |
| Phase 6 — Export Clean Dataset | ✅ | |

## **Phase 1 — Initial Setup & Dataset Understanding**

### #1.1 Import Library

In [1]:
import pandas as pd

### #1.2 Import Dataset

In [2]:
df = pd.read_excel('https://docs.google.com/spreadsheets/d/1CyBf7TxcxGoWRQiwRmzyI8ndo8KeCoUk/export?format=xlsx')

### # 1.3 Preview Dataset

In [3]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

### #1.4 Check Dataset Structure

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

### #1.5 Check Dataset Dimensions

In [5]:
df.shape

(1200, 14)

### #1.6 Generate Descriptive Statistics

In [6]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

## **PHASE 2 — Missing Value Analysis & Handling**

### #2.1 Check Missing Values

In [7]:
df.isnull().sum()

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

### #2.2 Analyze Missing Values

#### Findings

- A missing value analysis was performed to identify incomplete records.

- The results show that all columns are complete except for the `CouponCode` column, which contains 309 missing values.

- This is likely due to transactions where customers did not apply
a promotional coupon during checkout.

### #2.3 Handle Missing Values

In [8]:
df['CouponCode'] = df['CouponCode'].fillna('No Coupon')

### #2.4 Re-Check Missing Values

In [9]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

## **PHASE 3 — Duplicate Detection & Removal**

### #3.1 Check Duplicate Records

In [10]:
df.duplicated().sum()

np.int64(0)

Analysis of Duplicate Data

- A duplicate check was performed using
the `duplicated().sum()` function.

- The result shows that no duplicate records
were found in the dataset.

### #3.2 Remove Duplicate Records

In [11]:
df.drop_duplicates(inplace=True)

### #3.3 Validate Duplicate Removal

In [12]:
df.duplicated().sum()

np.int64(0)

- The dataset was revalidated after the duplicate handling process.

- The validation confirms that the dataset
contains zero duplicate records.

## **PHASE 4 — Data Formatting, Cleaning, & Validation**

### #4.1 Check Data Types

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

### #4.2 Date Formatting

In [14]:
df['Date'] = pd.to_datetime(df['Date'])

The `Date` column was converted into
datetime format to ensure consistency
and compatibility for future analysis.

### #4.3 Text Cleaning

In [15]:
text_columns = ['Product', 'ShippingAddress', 'PaymentMethod',
                'OrderStatus', 'ReferralSource']

for col in text_columns:
    df[col] = df[col].str.strip()

Text-based columns were cleaned using
the `str.strip()` method to remove
unnecessary leading and trailing spaces.

### #4.4 Numeric Data Validation

In [16]:
df[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']].dtypes

Quantity         int64
UnitPrice      float64
ItemsInCart      int64
TotalPrice     float64
dtype: object

Numeric columns were checked to ensure
they use appropriate numerical data types
for accurate calculations and analysis.

### #4.5 Validate Data Formats

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

- The dataset was validated after formatting and cleaning.

- All key columns now use consistent and appropriate
data formats for further analytical processes.

##**PHASE 5 — Final Data Validation**

### #5.1 Final Missing Value Validation

In [18]:
df.isnull().sum()

OrderID            0
Date               0
CustomerID         0
Product            0
Quantity           0
UnitPrice          0
ShippingAddress    0
PaymentMethod      0
OrderStatus        0
TrackingNumber     0
ItemsInCart        0
CouponCode         0
ReferralSource     0
TotalPrice         0
dtype: int64

### #5.2 Final Duplicate Validation

In [19]:
df.duplicated().sum()

np.int64(0)

### #5.3 Final Dataset Structure Validation

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   object
 1   Date             1200 non-null   datetime64[ns]
 2   CustomerID       1200 non-null   object
 3   Product          1200 non-null   object
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   object
 7   PaymentMethod    1200 non-null   object
 8   OrderStatus      1200 non-null   object
 9   TrackingNumber   1200 non-null   object
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   object
 12  ReferralSource   1200 non-null   object
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(9)
memory usage: 131.4+ KB

### #5.4 Final Dataset Preview

In [21]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

### #5.5 Validation Summary


The dataset has been successfully validated after
the cleaning and formatting processes.

Key validation results:
- No missing values remain
- No duplicate records found
- Data formats are consistent
- Dataset is ready for further analysis

##**PHASE 6 — Export Clean Dataset***

### #6.1 Export Clean Dataset (csv)

In [22]:
df.to_csv('clean_data.csv', index=False)

### #6.2 Export Clean Dataset (excel)

In [23]:
df.to_excel('clean_data.xlsx', index=False)

### #6.3 Final Project Summary

# Final Project Summary

The dataset cleaning and preparation process
has been successfully completed.

Key accomplishments:
- Missing values handled
- Duplicate records validated
- Data formats verified
- Dataset consistency ensured
- Clean dataset exported successfully

The dataset is now ready for
further analysis and visualization.